# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1011, 869)
        mainWindow.setMinimumSize(QtCore.QSize(1011, 869))
        mainWindow.setMaximumSize(QtCore.QSize(1011, 869))
        font = QtGui.QFont()
        font.setPointSize(11)
        mainWindow.setFont(font)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(377, 77, 611, 101))
        self.groupBox.setObjectName("groupBox")
        self.dstCheckbox = QtWidgets.QCheckBox(self.groupBox)
        self.dstCheckbox.setGeometry(QtCore.QRect(10, 70, 56, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dstCheckbox.sizePolicy().hasHeightForWidth())
        self.dstCheckbox.setSizePolicy(sizePolicy)
        self.dstCheckbox.setMinimumSize(QtCore.QSize(56, 22))
        self.dstCheckbox.setMaximumSize(QtCore.QSize(56, 22))
        self.dstCheckbox.setObjectName("dstCheckbox")
        self.dstLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dstLineEdit.setGeometry(QtCore.QRect(70, 70, 527, 24))
        self.dstLineEdit.setMinimumSize(QtCore.QSize(527, 24))
        self.dstLineEdit.setMaximumSize(QtCore.QSize(527, 24))
        self.dstLineEdit.setObjectName("dstLineEdit")
        self.srcCheckbox = QtWidgets.QCheckBox(self.groupBox)
        self.srcCheckbox.setGeometry(QtCore.QRect(10, 40, 56, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcCheckbox.sizePolicy().hasHeightForWidth())
        self.srcCheckbox.setSizePolicy(sizePolicy)
        self.srcCheckbox.setMinimumSize(QtCore.QSize(56, 22))
        self.srcCheckbox.setMaximumSize(QtCore.QSize(56, 22))
        self.srcCheckbox.setObjectName("srcCheckbox")
        self.srcLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.srcLineEdit.setGeometry(QtCore.QRect(70, 40, 527, 24))
        self.srcLineEdit.setMinimumSize(QtCore.QSize(527, 24))
        self.srcLineEdit.setMaximumSize(QtCore.QSize(527, 24))
        self.srcLineEdit.setObjectName("srcLineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 183, 611, 201))
        self.groupBox_2.setMinimumSize(QtCore.QSize(611, 201))
        self.groupBox_2.setMaximumSize(QtCore.QSize(611, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.optionsIpLabel = QtWidgets.QLabel(self.groupBox_2)
        self.optionsIpLabel.setGeometry(QtCore.QRect(300, 170, 71, 24))
        self.optionsIpLabel.setObjectName("optionsIpLabel")
        self.optionsIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.optionsIpLineEdit.setGeometry(QtCore.QRect(378, 170, 221, 24))
        self.optionsIpLineEdit.setText("")
        self.optionsIpLineEdit.setObjectName("optionsIpLineEdit")
        self.dscpIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.dscpIpLineEdit.setGeometry(QtCore.QRect(150, 100, 161, 24))
        self.dscpIpLineEdit.setObjectName("dscpIpLineEdit")
        self.srcVerCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.srcVerCheckbox.setGeometry(QtCore.QRect(324, 32, 54, 22))
        self.srcVerCheckbox.setMinimumSize(QtCore.QSize(54, 22))
        self.srcVerCheckbox.setMaximumSize(QtCore.QSize(54, 22))
        self.srcVerCheckbox.setObjectName("srcVerCheckbox")
        self.verLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.verLineEdit.setGeometry(QtCore.QRect(384, 31, 211, 24))
        self.verLineEdit.setObjectName("verLineEdit")
        self.offsetLabel = QtWidgets.QLabel(self.groupBox_2)
        self.offsetLabel.setGeometry(QtCore.QRect(17, 134, 58, 26))
        self.offsetLabel.setMinimumSize(QtCore.QSize(58, 26))
        self.offsetLabel.setMaximumSize(QtCore.QSize(58, 26))
        self.offsetLabel.setObjectName("offsetLabel")
        self.offsetLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.offsetLineEdit.setGeometry(QtCore.QRect(81, 135, 233, 24))
        self.offsetLineEdit.setMinimumSize(QtCore.QSize(233, 24))
        self.offsetLineEdit.setMaximumSize(QtCore.QSize(233, 24))
        self.offsetLineEdit.setObjectName("offsetLineEdit")
        self.lenIpCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.lenIpCheckbox.setGeometry(QtCore.QRect(324, 64, 54, 22))
        self.lenIpCheckbox.setMinimumSize(QtCore.QSize(54, 22))
        self.lenIpCheckbox.setMaximumSize(QtCore.QSize(53, 22))
        self.lenIpCheckbox.setObjectName("lenIpCheckbox")
        self.lenIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lenIpLineEdit.setGeometry(QtCore.QRect(384, 63, 211, 24))
        self.lenIpLineEdit.setObjectName("lenIpLineEdit")
        self.dstIpLabel = QtWidgets.QLabel(self.groupBox_2)
        self.dstIpLabel.setGeometry(QtCore.QRect(17, 69, 52, 24))
        self.dstIpLabel.setMinimumSize(QtCore.QSize(52, 24))
        self.dstIpLabel.setMaximumSize(QtCore.QSize(52, 24))
        self.dstIpLabel.setObjectName("dstIpLabel")
        self.dstIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.dstIpLineEdit.setGeometry(QtCore.QRect(75, 69, 229, 24))
        self.dstIpLineEdit.setMinimumSize(QtCore.QSize(229, 24))
        self.dstIpLineEdit.setMaximumSize(QtCore.QSize(239, 24))
        self.dstIpLineEdit.setText("")
        self.dstIpLineEdit.setObjectName("dstIpLineEdit")
        self.srcIpCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.srcIpCheckbox.setGeometry(QtCore.QRect(17, 38, 73, 22))
        self.srcIpCheckbox.setMinimumSize(QtCore.QSize(73, 22))
        self.srcIpCheckbox.setMaximumSize(QtCore.QSize(73, 22))
        self.srcIpCheckbox.setObjectName("srcIpCheckbox")
        self.srcIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.srcIpLineEdit.setGeometry(QtCore.QRect(96, 37, 208, 24))
        self.srcIpLineEdit.setMinimumSize(QtCore.QSize(208, 24))
        self.srcIpLineEdit.setMaximumSize(QtCore.QSize(218, 24))
        self.srcIpLineEdit.setText("")
        self.srcIpLineEdit.setObjectName("srcIpLineEdit")
        self.ttlLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.ttlLineEdit.setGeometry(QtCore.QRect(55, 168, 71, 24))
        self.ttlLineEdit.setObjectName("ttlLineEdit")
        self.ttlLabel = QtWidgets.QLabel(self.groupBox_2)
        self.ttlLabel.setGeometry(QtCore.QRect(17, 168, 32, 25))
        self.ttlLabel.setMinimumSize(QtCore.QSize(32, 25))
        self.ttlLabel.setMaximumSize(QtCore.QSize(32, 25))
        self.ttlLabel.setObjectName("ttlLabel")
        self.checksumCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checksumCheckbox.setGeometry(QtCore.QRect(324, 128, 103, 22))
        self.checksumCheckbox.setMinimumSize(QtCore.QSize(103, 22))
        self.checksumCheckbox.setMaximumSize(QtCore.QSize(103, 22))
        self.checksumCheckbox.setObjectName("checksumCheckbox")
        self.checksumIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.checksumIpLineEdit.setGeometry(QtCore.QRect(433, 127, 161, 24))
        self.checksumIpLineEdit.setText("")
        self.checksumIpLineEdit.setObjectName("checksumIpLineEdit")
        self.flag0Checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.flag0Checkbox.setGeometry(QtCore.QRect(166, 170, 31, 22))
        self.flag0Checkbox.setMinimumSize(QtCore.QSize(31, 22))
        self.flag0Checkbox.setMaximumSize(QtCore.QSize(31, 22))
        self.flag0Checkbox.setObjectName("flag0Checkbox")
        self.flagDfCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.flagDfCheckbox.setGeometry(QtCore.QRect(203, 170, 41, 22))
        self.flagDfCheckbox.setMinimumSize(QtCore.QSize(41, 22))
        self.flagDfCheckbox.setMaximumSize(QtCore.QSize(41, 22))
        self.flagDfCheckbox.setObjectName("flagDfCheckbox")
        self.flagMfCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.flagMfCheckbox.setGeometry(QtCore.QRect(250, 170, 43, 22))
        self.flagMfCheckbox.setMinimumSize(QtCore.QSize(43, 22))
        self.flagMfCheckbox.setMaximumSize(QtCore.QSize(43, 22))
        self.flagMfCheckbox.setObjectName("flagMfCheckbox")
        self.idLabel = QtWidgets.QLabel(self.groupBox_2)
        self.idLabel.setGeometry(QtCore.QRect(324, 95, 21, 24))
        self.idLabel.setMinimumSize(QtCore.QSize(21, 24))
        self.idLabel.setMaximumSize(QtCore.QSize(21, 24))
        self.idLabel.setObjectName("idLabel")
        self.idLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.idLineEdit.setGeometry(QtCore.QRect(351, 95, 241, 24))
        self.idLineEdit.setObjectName("idLineEdit")
        self.dscpLabel = QtWidgets.QLabel(self.groupBox_2)
        self.dscpLabel.setGeometry(QtCore.QRect(17, 101, 100, 25))
        self.dscpLabel.setMinimumSize(QtCore.QSize(100, 25))
        self.dscpLabel.setMaximumSize(QtCore.QSize(100, 25))
        self.dscpLabel.setObjectName("dscpLabel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 390, 611, 241))
        self.groupBox_3.setMinimumSize(QtCore.QSize(611, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.windowCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.windowCheckbox.setGeometry(QtCore.QRect(13, 161, 93, 22))
        self.windowCheckbox.setMinimumSize(QtCore.QSize(93, 22))
        self.windowCheckbox.setMaximumSize(QtCore.QSize(93, 22))
        self.windowCheckbox.setObjectName("windowCheckbox")
        self.reservedLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.reservedLineEdit.setGeometry(QtCore.QRect(350, 100, 251, 24))
        self.reservedLineEdit.setObjectName("reservedLineEdit")
        self.addToListPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.addToListPushButton.setGeometry(QtCore.QRect(520, 200, 75, 26))
        self.addToListPushButton.setObjectName("addToListPushButton")
        self.urgCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.urgCheckbox.setGeometry(QtCore.QRect(276, 170, 52, 22))
        self.urgCheckbox.setMinimumSize(QtCore.QSize(52, 22))
        self.urgCheckbox.setMaximumSize(QtCore.QSize(52, 22))
        self.urgCheckbox.setObjectName("urgCheckbox")
        self.urgPtrLabel = QtWidgets.QLabel(self.groupBox_3)
        self.urgPtrLabel.setEnabled(False)
        self.urgPtrLabel.setGeometry(QtCore.QRect(334, 169, 66, 24))
        self.urgPtrLabel.setMinimumSize(QtCore.QSize(66, 24))
        self.urgPtrLabel.setMaximumSize(QtCore.QSize(66, 24))
        self.urgPtrLabel.setObjectName("urgPtrLabel")
        self.urgPtrLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.urgPtrLineEdit.setEnabled(False)
        self.urgPtrLineEdit.setGeometry(QtCore.QRect(406, 169, 193, 24))
        self.urgPtrLineEdit.setMinimumSize(QtCore.QSize(193, 24))
        self.urgPtrLineEdit.setMaximumSize(QtCore.QSize(193, 24))
        self.urgPtrLineEdit.setText("")
        self.urgPtrLineEdit.setObjectName("urgPtrLineEdit")
        self.reservedLabel = QtWidgets.QLabel(self.groupBox_3)
        self.reservedLabel.setGeometry(QtCore.QRect(276, 106, 74, 22))
        self.reservedLabel.setMinimumSize(QtCore.QSize(74, 22))
        self.reservedLabel.setMaximumSize(QtCore.QSize(74, 22))
        self.reservedLabel.setObjectName("reservedLabel")
        self.synCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.synCheckbox.setGeometry(QtCore.QRect(489, 33, 51, 22))
        self.synCheckbox.setMinimumSize(QtCore.QSize(51, 22))
        self.synCheckbox.setMaximumSize(QtCore.QSize(51, 22))
        self.synCheckbox.setObjectName("synCheckbox")
        self.pshCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.pshCheckbox.setGeometry(QtCore.QRect(546, 33, 50, 22))
        self.pshCheckbox.setMinimumSize(QtCore.QSize(50, 22))
        self.pshCheckbox.setMaximumSize(QtCore.QSize(50, 22))
        self.pshCheckbox.setObjectName("pshCheckbox")
        self.ackCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.ackCheckbox.setGeometry(QtCore.QRect(489, 57, 51, 22))
        self.ackCheckbox.setMinimumSize(QtCore.QSize(51, 22))
        self.ackCheckbox.setMaximumSize(QtCore.QSize(51, 22))
        self.ackCheckbox.setObjectName("ackCheckbox")
        self.rstCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.rstCheckbox.setGeometry(QtCore.QRect(546, 57, 50, 22))
        self.rstCheckbox.setMinimumSize(QtCore.QSize(50, 22))
        self.rstCheckbox.setMaximumSize(QtCore.QSize(50, 22))
        self.rstCheckbox.setObjectName("rstCheckbox")
        self.finCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.finCheckbox.setGeometry(QtCore.QRect(489, 80, 51, 22))
        self.finCheckbox.setMinimumSize(QtCore.QSize(51, 22))
        self.finCheckbox.setMaximumSize(QtCore.QSize(51, 22))
        self.finCheckbox.setObjectName("finCheckbox")
        self.srcPortLabel = QtWidgets.QLabel(self.groupBox_3)
        self.srcPortLabel.setGeometry(QtCore.QRect(13, 31, 74, 25))
        self.srcPortLabel.setMinimumSize(QtCore.QSize(74, 25))
        self.srcPortLabel.setMaximumSize(QtCore.QSize(74, 25))
        self.srcPortLabel.setObjectName("srcPortLabel")
        self.srcPortLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.srcPortLineEdit.setGeometry(QtCore.QRect(93, 31, 172, 24))
        self.srcPortLineEdit.setMinimumSize(QtCore.QSize(172, 24))
        self.srcPortLineEdit.setMaximumSize(QtCore.QSize(172, 24))
        self.srcPortLineEdit.setText("")
        self.srcPortLineEdit.setObjectName("srcPortLineEdit")
        self.windowLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.windowLineEdit.setGeometry(QtCore.QRect(112, 160, 153, 24))
        self.windowLineEdit.setMinimumSize(QtCore.QSize(153, 24))
        self.windowLineEdit.setMaximumSize(QtCore.QSize(153, 24))
        self.windowLineEdit.setObjectName("windowLineEdit")
        self.dstPortLabel = QtWidgets.QLabel(self.groupBox_3)
        self.dstPortLabel.setGeometry(QtCore.QRect(13, 64, 76, 24))
        self.dstPortLabel.setMinimumSize(QtCore.QSize(76, 24))
        self.dstPortLabel.setMaximumSize(QtCore.QSize(76, 24))
        self.dstPortLabel.setObjectName("dstPortLabel")
        self.dstPortLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.dstPortLineEdit.setGeometry(QtCore.QRect(95, 64, 170, 24))
        self.dstPortLineEdit.setMinimumSize(QtCore.QSize(170, 24))
        self.dstPortLineEdit.setMaximumSize(QtCore.QSize(170, 24))
        self.dstPortLineEdit.setText("")
        self.dstPortLineEdit.setObjectName("dstPortLineEdit")
        self.ackLabel = QtWidgets.QLabel(self.groupBox_3)
        self.ackLabel.setGeometry(QtCore.QRect(278, 70, 55, 24))
        self.ackLabel.setMinimumSize(QtCore.QSize(55, 24))
        self.ackLabel.setMaximumSize(QtCore.QSize(55, 24))
        self.ackLabel.setObjectName("ackLabel")
        self.ackLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.ackLineEdit.setGeometry(QtCore.QRect(339, 70, 143, 24))
        self.ackLineEdit.setMinimumSize(QtCore.QSize(143, 24))
        self.ackLineEdit.setMaximumSize(QtCore.QSize(143, 24))
        self.ackLineEdit.setObjectName("ackLineEdit")
        self.checksumHeaderCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checksumHeaderCheckbox.setGeometry(QtCore.QRect(13, 129, 103, 22))
        self.checksumHeaderCheckbox.setMinimumSize(QtCore.QSize(103, 22))
        self.checksumHeaderCheckbox.setMaximumSize(QtCore.QSize(103, 22))
        self.checksumHeaderCheckbox.setObjectName("checksumHeaderCheckbox")
        self.checksumLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.checksumLineEdit.setGeometry(QtCore.QRect(122, 128, 143, 24))
        self.checksumLineEdit.setMinimumSize(QtCore.QSize(143, 24))
        self.checksumLineEdit.setMaximumSize(QtCore.QSize(143, 24))
        self.checksumLineEdit.setText("")
        self.checksumLineEdit.setObjectName("checksumLineEdit")
        self.optionsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.optionsLabel.setGeometry(QtCore.QRect(276, 136, 69, 25))
        self.optionsLabel.setMinimumSize(QtCore.QSize(69, 25))
        self.optionsLabel.setMaximumSize(QtCore.QSize(69, 25))
        self.optionsLabel.setObjectName("optionsLabel")
        self.optionsLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.optionsLineEdit.setGeometry(QtCore.QRect(351, 136, 248, 24))
        self.optionsLineEdit.setMinimumSize(QtCore.QSize(248, 24))
        self.optionsLineEdit.setMaximumSize(QtCore.QSize(248, 24))
        self.optionsLineEdit.setText("")
        self.optionsLineEdit.setObjectName("optionsLineEdit")
        self.snLabel = QtWidgets.QLabel(self.groupBox_3)
        self.snLabel.setGeometry(QtCore.QRect(278, 35, 23, 24))
        self.snLabel.setMinimumSize(QtCore.QSize(23, 24))
        self.snLabel.setMaximumSize(QtCore.QSize(23, 24))
        self.snLabel.setObjectName("snLabel")
        self.snLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.snLineEdit.setGeometry(QtCore.QRect(307, 35, 175, 24))
        self.snLineEdit.setMinimumSize(QtCore.QSize(175, 24))
        self.snLineEdit.setMaximumSize(QtCore.QSize(175, 24))
        self.snLineEdit.setObjectName("snLineEdit")
        self.lenCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.lenCheckbox.setGeometry(QtCore.QRect(13, 97, 53, 22))
        self.lenCheckbox.setMinimumSize(QtCore.QSize(53, 22))
        self.lenCheckbox.setMaximumSize(QtCore.QSize(53, 22))
        self.lenCheckbox.setObjectName("lenCheckbox")
        self.lenLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lenLineEdit.setGeometry(QtCore.QRect(72, 96, 193, 24))
        self.lenLineEdit.setMinimumSize(QtCore.QSize(193, 24))
        self.lenLineEdit.setMaximumSize(QtCore.QSize(193, 24))
        self.lenLineEdit.setText("")
        self.lenLineEdit.setObjectName("lenLineEdit")
        self.packetLabel = QtWidgets.QLabel(self.centralwidget)
        self.packetLabel.setGeometry(QtCore.QRect(23, 13, 344, 39))
        self.packetLabel.setMinimumSize(QtCore.QSize(344, 39))
        self.packetLabel.setMaximumSize(QtCore.QSize(344, 39))
        self.packetLabel.setObjectName("packetLabel")
        self.queueLabel = QtWidgets.QLabel(self.centralwidget)
        self.queueLabel.setGeometry(QtCore.QRect(23, 311, 344, 38))
        self.queueLabel.setMinimumSize(QtCore.QSize(344, 38))
        self.queueLabel.setMaximumSize(QtCore.QSize(344, 38))
        self.queueLabel.setObjectName("queueLabel")
        self.queueListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.queueListWidget.setGeometry(QtCore.QRect(24, 356, 341, 201))
        self.queueListWidget.setMinimumSize(QtCore.QSize(341, 201))
        self.queueListWidget.setMaximumSize(QtCore.QSize(341, 201))
        self.queueListWidget.setObjectName("queueListWidget")
        self.packetList = QtWidgets.QListWidget(self.centralwidget)
        self.packetList.setGeometry(QtCore.QRect(24, 59, 341, 201))
        self.packetList.setMinimumSize(QtCore.QSize(341, 201))
        self.packetList.setMaximumSize(QtCore.QSize(341, 201))
        self.packetList.setObjectName("packetList")
        self.addListPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addListPushButton.setGeometry(QtCore.QRect(25, 272, 96, 26))
        self.addListPushButton.setMinimumSize(QtCore.QSize(96, 26))
        self.addListPushButton.setMaximumSize(QtCore.QSize(96, 26))
        self.addListPushButton.setObjectName("addListPushButton")
        self.removeListPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeListPushButton.setGeometry(QtCore.QRect(292, 272, 75, 26))
        self.removeListPushButton.setMinimumSize(QtCore.QSize(75, 26))
        self.removeListPushButton.setMaximumSize(QtCore.QSize(75, 26))
        self.removeListPushButton.setObjectName("removeListPushButton")
        self.packetNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.packetNameLabel.setGeometry(QtCore.QRect(378, 46, 92, 24))
        self.packetNameLabel.setMinimumSize(QtCore.QSize(92, 24))
        self.packetNameLabel.setMaximumSize(QtCore.QSize(92, 24))
        self.packetNameLabel.setObjectName("packetNameLabel")
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setGeometry(QtCore.QRect(476, 46, 511, 24))
        self.nameLineEdit.setMinimumSize(QtCore.QSize(511, 24))
        self.nameLineEdit.setMaximumSize(QtCore.QSize(511, 24))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.packetTypeBox = QtWidgets.QComboBox(self.centralwidget)
        self.packetTypeBox.setGeometry(QtCore.QRect(378, 14, 302, 24))
        self.packetTypeBox.setMinimumSize(QtCore.QSize(302, 24))
        self.packetTypeBox.setMaximumSize(QtCore.QSize(302, 24))
        self.packetTypeBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.packetTypeBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.packetTypeBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.packetTypeBox.setObjectName("packetTypeBox")
        self.packetTypeBox.addItem("")
        self.packetTypeBox.addItem("")
        self.packetTypeBox.addItem("")
        self.packetTypeBox.addItem("")
        self.adaptersBox = QtWidgets.QComboBox(self.centralwidget)
        self.adaptersBox.setGeometry(QtCore.QRect(686, 14, 301, 24))
        self.adaptersBox.setMinimumSize(QtCore.QSize(301, 24))
        self.adaptersBox.setMaximumSize(QtCore.QSize(301, 24))
        self.adaptersBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.adaptersBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.adaptersBox.setObjectName("adaptersBox")
        self.adaptersBox.addItem("")
        self.sendQueuePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendQueuePushButton.setGeometry(QtCore.QRect(25, 564, 75, 26))
        self.sendQueuePushButton.setMinimumSize(QtCore.QSize(75, 26))
        self.sendQueuePushButton.setMaximumSize(QtCore.QSize(75, 26))
        self.sendQueuePushButton.setObjectName("sendQueuePushButton")
        self.removeQueuePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeQueuePushButton.setGeometry(QtCore.QRect(159, 564, 75, 26))
        self.removeQueuePushButton.setMinimumSize(QtCore.QSize(75, 26))
        self.removeQueuePushButton.setMaximumSize(QtCore.QSize(75, 26))
        self.removeQueuePushButton.setObjectName("removeQueuePushButton")
        self.cleanQueuePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.cleanQueuePushButton.setGeometry(QtCore.QRect(292, 564, 75, 26))
        self.cleanQueuePushButton.setMinimumSize(QtCore.QSize(75, 26))
        self.cleanQueuePushButton.setMaximumSize(QtCore.QSize(75, 26))
        self.cleanQueuePushButton.setObjectName("cleanQueuePushButton")
        self.dataLabel = QtWidgets.QLabel(self.centralwidget)
        self.dataLabel.setGeometry(QtCore.QRect(20, 630, 967, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataLabel.sizePolicy().hasHeightForWidth())
        self.dataLabel.setSizePolicy(sizePolicy)
        self.dataLabel.setMinimumSize(QtCore.QSize(967, 18))
        self.dataLabel.setMaximumSize(QtCore.QSize(967, 18))
        self.dataLabel.setObjectName("dataLabel")
        self.dataTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.dataTextEdit.setGeometry(QtCore.QRect(20, 660, 951, 191))
        self.dataTextEdit.setObjectName("dataTextEdit")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Packet Generator by Tsvetkov"))
        self.groupBox.setTitle(_translate("mainWindow", "Data link layer - Ethernet"))
        self.dstCheckbox.setText(_translate("mainWindow", "DST:"))
        self.srcCheckbox.setText(_translate("mainWindow", "SRC:"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Network layer - IPv4"))
        self.optionsIpLabel.setText(_translate("mainWindow", "OPTIONS:"))
        self.dscpIpLineEdit.setText(_translate("mainWindow", "0"))
        self.srcVerCheckbox.setText(_translate("mainWindow", "VER:"))
        self.verLineEdit.setText(_translate("mainWindow", "4"))
        self.offsetLabel.setText(_translate("mainWindow", "OFFSET:"))
        self.offsetLineEdit.setText(_translate("mainWindow", "0"))
        self.lenIpCheckbox.setText(_translate("mainWindow", "LEN:"))
        self.lenIpLineEdit.setText(_translate("mainWindow", "0"))
        self.dstIpLabel.setText(_translate("mainWindow", "DST IP:"))
        self.srcIpCheckbox.setText(_translate("mainWindow", "SRC IP:"))
        self.ttlLineEdit.setText(_translate("mainWindow", "64"))
        self.ttlLabel.setText(_translate("mainWindow", "TTL:"))
        self.checksumCheckbox.setText(_translate("mainWindow", "CHECKSUM:"))
        self.flag0Checkbox.setText(_translate("mainWindow", "0"))
        self.flagDfCheckbox.setText(_translate("mainWindow", "DF"))
        self.flagMfCheckbox.setText(_translate("mainWindow", "MF"))
        self.idLabel.setText(_translate("mainWindow", "ID:"))
        self.idLineEdit.setText(_translate("mainWindow", "0"))
        self.dscpLabel.setText(_translate("mainWindow", "DSCP (Priority):"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Transport level"))
        self.windowCheckbox.setText(_translate("mainWindow", "WINDOW:"))
        self.reservedLineEdit.setText(_translate("mainWindow", "0"))
        self.addToListPushButton.setText(_translate("mainWindow", "Add to list"))
        self.urgCheckbox.setText(_translate("mainWindow", "URG"))
        self.urgPtrLabel.setText(_translate("mainWindow", "URG PTR:"))
        self.reservedLabel.setText(_translate("mainWindow", "RESERVED:"))
        self.synCheckbox.setText(_translate("mainWindow", "SYN"))
        self.pshCheckbox.setText(_translate("mainWindow", "PSH"))
        self.ackCheckbox.setText(_translate("mainWindow", "ACK"))
        self.rstCheckbox.setText(_translate("mainWindow", "RST"))
        self.finCheckbox.setText(_translate("mainWindow", "FIN"))
        self.srcPortLabel.setText(_translate("mainWindow", "SRC PORT:"))
        self.windowLineEdit.setText(_translate("mainWindow", "0"))
        self.dstPortLabel.setText(_translate("mainWindow", "DST PORT:"))
        self.ackLabel.setText(_translate("mainWindow", "ACK SN:"))
        self.ackLineEdit.setText(_translate("mainWindow", "0"))
        self.checksumHeaderCheckbox.setText(_translate("mainWindow", "CHECKSUM:"))
        self.optionsLabel.setText(_translate("mainWindow", "OPTIONS:"))
        self.snLabel.setText(_translate("mainWindow", "SN:"))
        self.snLineEdit.setText(_translate("mainWindow", "0"))
        self.lenCheckbox.setText(_translate("mainWindow", "LEN:"))
        self.packetLabel.setText(_translate("mainWindow", "Packet List:"))
        self.queueLabel.setText(_translate("mainWindow", "Packet Sending Queue:"))
        self.addListPushButton.setText(_translate("mainWindow", "Add to queue"))
        self.removeListPushButton.setText(_translate("mainWindow", "Remove"))
        self.packetNameLabel.setText(_translate("mainWindow", "Packet Name:"))
        self.packetTypeBox.setItemText(0, _translate("mainWindow", "TCP"))
        self.packetTypeBox.setItemText(1, _translate("mainWindow", "UDP"))
        self.packetTypeBox.setItemText(2, _translate("mainWindow", "ICMP - echo request"))
        self.packetTypeBox.setItemText(3, _translate("mainWindow", "ICMP - echo reply"))
        self.adaptersBox.setItemText(0, _translate("mainWindow", "Choose network interface"))
        self.sendQueuePushButton.setText(_translate("mainWindow", "Send"))
        self.removeQueuePushButton.setText(_translate("mainWindow", "Remove"))
        self.cleanQueuePushButton.setText(_translate("mainWindow", "Clean"))
        self.dataLabel.setText(_translate("mainWindow", "Data:"))
