# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1011, 938)
        mainWindow.setMinimumSize(QtCore.QSize(1011, 938))
        font = QtGui.QFont()
        font.setPointSize(11)
        mainWindow.setFont(font)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.packetLabel = QtWidgets.QLabel(self.centralwidget)
        self.packetLabel.setMinimumSize(QtCore.QSize(344, 39))
        self.packetLabel.setMaximumSize(QtCore.QSize(344, 39))
        self.packetLabel.setObjectName("packetLabel")
        self.verticalLayout.addWidget(self.packetLabel)
        self.packetList = QtWidgets.QListWidget(self.centralwidget)
        self.packetList.setObjectName("packetList")
        self.verticalLayout.addWidget(self.packetList)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.addListPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addListPushButton.setObjectName("addListPushButton")
        self.horizontalLayout_26.addWidget(self.addListPushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)
        self.removeListPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeListPushButton.setMinimumSize(QtCore.QSize(75, 26))
        self.removeListPushButton.setMaximumSize(QtCore.QSize(75, 26))
        self.removeListPushButton.setObjectName("removeListPushButton")
        self.horizontalLayout_26.addWidget(self.removeListPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 4, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.packetTypeBox = QtWidgets.QComboBox(self.centralwidget)
        self.packetTypeBox.setMaximumSize(QtCore.QSize(191, 16777215))
        self.packetTypeBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.packetTypeBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.packetTypeBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.packetTypeBox.setObjectName("packetTypeBox")
        self.packetTypeBox.addItem("")
        self.packetTypeBox.addItem("")
        self.packetTypeBox.addItem("")
        self.packetTypeBox.addItem("")
        self.horizontalLayout.addWidget(self.packetTypeBox)
        self.adaptersBox = QtWidgets.QComboBox(self.centralwidget)
        self.adaptersBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.adaptersBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.adaptersBox.setObjectName("adaptersBox")
        self.adaptersBox.addItem("")
        self.horizontalLayout.addWidget(self.adaptersBox)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.packetNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.packetNameLabel.setObjectName("packetNameLabel")
        self.horizontalLayout_2.addWidget(self.packetNameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.horizontalLayout_2.addWidget(self.nameLineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.srcCheckbox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcCheckbox.sizePolicy().hasHeightForWidth())
        self.srcCheckbox.setSizePolicy(sizePolicy)
        self.srcCheckbox.setMinimumSize(QtCore.QSize(56, 22))
        self.srcCheckbox.setMaximumSize(QtCore.QSize(56, 22))
        self.srcCheckbox.setObjectName("srcCheckbox")
        self.horizontalLayout_3.addWidget(self.srcCheckbox)
        self.srcLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.srcLineEdit.setMinimumSize(QtCore.QSize(527, 24))
        self.srcLineEdit.setMaximumSize(QtCore.QSize(527, 24))
        self.srcLineEdit.setObjectName("srcLineEdit")
        self.horizontalLayout_3.addWidget(self.srcLineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dstCheckbox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dstCheckbox.sizePolicy().hasHeightForWidth())
        self.dstCheckbox.setSizePolicy(sizePolicy)
        self.dstCheckbox.setMinimumSize(QtCore.QSize(56, 22))
        self.dstCheckbox.setMaximumSize(QtCore.QSize(56, 22))
        self.dstCheckbox.setObjectName("dstCheckbox")
        self.horizontalLayout_4.addWidget(self.dstCheckbox)
        self.dstLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dstLineEdit.setMinimumSize(QtCore.QSize(527, 24))
        self.dstLineEdit.setMaximumSize(QtCore.QSize(527, 24))
        self.dstLineEdit.setObjectName("dstLineEdit")
        self.horizontalLayout_4.addWidget(self.dstLineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lenIpCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.lenIpCheckbox.setObjectName("lenIpCheckbox")
        self.horizontalLayout_8.addWidget(self.lenIpCheckbox)
        self.lenIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lenIpLineEdit.setObjectName("lenIpLineEdit")
        self.horizontalLayout_8.addWidget(self.lenIpLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 2, 2, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.offsetLabel = QtWidgets.QLabel(self.groupBox_2)
        self.offsetLabel.setObjectName("offsetLabel")
        self.horizontalLayout_25.addWidget(self.offsetLabel)
        self.offsetLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.offsetLineEdit.setObjectName("offsetLineEdit")
        self.horizontalLayout_25.addWidget(self.offsetLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_25, 5, 0, 1, 2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.flag0Checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.flag0Checkbox.setObjectName("flag0Checkbox")
        self.horizontalLayout_12.addWidget(self.flag0Checkbox)
        self.flagDfCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.flagDfCheckbox.setObjectName("flagDfCheckbox")
        self.horizontalLayout_12.addWidget(self.flagDfCheckbox)
        self.flagMfCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.flagMfCheckbox.setObjectName("flagMfCheckbox")
        self.horizontalLayout_12.addWidget(self.flagMfCheckbox)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 6, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checksumCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checksumCheckbox.setObjectName("checksumCheckbox")
        self.horizontalLayout_10.addWidget(self.checksumCheckbox)
        self.checksumIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.checksumIpLineEdit.setText("")
        self.checksumIpLineEdit.setObjectName("checksumIpLineEdit")
        self.horizontalLayout_10.addWidget(self.checksumIpLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 5, 2, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.optionsIpLabel = QtWidgets.QLabel(self.groupBox_2)
        self.optionsIpLabel.setObjectName("optionsIpLabel")
        self.horizontalLayout_11.addWidget(self.optionsIpLabel)
        self.optionsIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.optionsIpLineEdit.setText("")
        self.optionsIpLineEdit.setObjectName("optionsIpLineEdit")
        self.horizontalLayout_11.addWidget(self.optionsIpLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 6, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.idLabel = QtWidgets.QLabel(self.groupBox_2)
        self.idLabel.setObjectName("idLabel")
        self.horizontalLayout_9.addWidget(self.idLabel)
        self.idLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.idLineEdit.setObjectName("idLineEdit")
        self.horizontalLayout_9.addWidget(self.idLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 3, 2, 2, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.srcIpCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.srcIpCheckbox.setObjectName("srcIpCheckbox")
        self.horizontalLayout_5.addWidget(self.srcIpCheckbox)
        self.srcIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.srcIpLineEdit.setText("")
        self.srcIpLineEdit.setObjectName("srcIpLineEdit")
        self.horizontalLayout_5.addWidget(self.srcIpLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 2, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.dstIpLabel = QtWidgets.QLabel(self.groupBox_2)
        self.dstIpLabel.setObjectName("dstIpLabel")
        self.horizontalLayout_6.addWidget(self.dstIpLabel)
        self.dstIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.dstIpLineEdit.setText("")
        self.dstIpLineEdit.setObjectName("dstIpLineEdit")
        self.horizontalLayout_6.addWidget(self.dstIpLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 2, 0, 2, 2)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.dscpLabel = QtWidgets.QLabel(self.groupBox_2)
        self.dscpLabel.setObjectName("dscpLabel")
        self.horizontalLayout_24.addWidget(self.dscpLabel)
        self.dscpIpLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.dscpIpLineEdit.setObjectName("dscpIpLineEdit")
        self.horizontalLayout_24.addWidget(self.dscpIpLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_24, 4, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.srcVerCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.srcVerCheckbox.setObjectName("srcVerCheckbox")
        self.horizontalLayout_7.addWidget(self.srcVerCheckbox)
        self.verLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.verLineEdit.setObjectName("verLineEdit")
        self.horizontalLayout_7.addWidget(self.verLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 2, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ttlLabel = QtWidgets.QLabel(self.groupBox_2)
        self.ttlLabel.setObjectName("ttlLabel")
        self.horizontalLayout_13.addWidget(self.ttlLabel)
        self.ttlLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.ttlLineEdit.setObjectName("ttlLineEdit")
        self.horizontalLayout_13.addWidget(self.ttlLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 6, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 3, 1, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.queueLabel = QtWidgets.QLabel(self.centralwidget)
        self.queueLabel.setMinimumSize(QtCore.QSize(344, 38))
        self.queueLabel.setMaximumSize(QtCore.QSize(344, 38))
        self.queueLabel.setObjectName("queueLabel")
        self.verticalLayout_2.addWidget(self.queueLabel)
        self.queueListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.queueListWidget.setObjectName("queueListWidget")
        self.verticalLayout_2.addWidget(self.queueListWidget)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.sendQueuePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendQueuePushButton.setMinimumSize(QtCore.QSize(75, 26))
        self.sendQueuePushButton.setMaximumSize(QtCore.QSize(75, 26))
        self.sendQueuePushButton.setObjectName("sendQueuePushButton")
        self.horizontalLayout_27.addWidget(self.sendQueuePushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem1)
        self.removeQueuePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeQueuePushButton.setMinimumSize(QtCore.QSize(75, 26))
        self.removeQueuePushButton.setMaximumSize(QtCore.QSize(75, 26))
        self.removeQueuePushButton.setObjectName("removeQueuePushButton")
        self.horizontalLayout_27.addWidget(self.removeQueuePushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 4, 0, 2, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 308))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.srcPortLabel = QtWidgets.QLabel(self.groupBox_3)
        self.srcPortLabel.setObjectName("srcPortLabel")
        self.horizontalLayout_14.addWidget(self.srcPortLabel)
        self.srcPortLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.srcPortLineEdit.setText("")
        self.srcPortLineEdit.setObjectName("srcPortLineEdit")
        self.horizontalLayout_14.addWidget(self.srcPortLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_14, 0, 0, 1, 2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.snLabel = QtWidgets.QLabel(self.groupBox_3)
        self.snLabel.setObjectName("snLabel")
        self.horizontalLayout_17.addWidget(self.snLabel)
        self.snLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.snLineEdit.setObjectName("snLineEdit")
        self.horizontalLayout_17.addWidget(self.snLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_17, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.synCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.synCheckbox.setObjectName("synCheckbox")
        self.gridLayout.addWidget(self.synCheckbox, 0, 0, 1, 1)
        self.pshCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.pshCheckbox.setObjectName("pshCheckbox")
        self.gridLayout.addWidget(self.pshCheckbox, 0, 1, 1, 1)
        self.ackCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.ackCheckbox.setObjectName("ackCheckbox")
        self.gridLayout.addWidget(self.ackCheckbox, 1, 0, 1, 1)
        self.rstCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.rstCheckbox.setObjectName("rstCheckbox")
        self.gridLayout.addWidget(self.rstCheckbox, 1, 1, 1, 1)
        self.finCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.finCheckbox.setObjectName("finCheckbox")
        self.gridLayout.addWidget(self.finCheckbox, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 3, 2, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.dstPortLabel = QtWidgets.QLabel(self.groupBox_3)
        self.dstPortLabel.setObjectName("dstPortLabel")
        self.horizontalLayout_15.addWidget(self.dstPortLabel)
        self.dstPortLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.dstPortLineEdit.setText("")
        self.dstPortLineEdit.setObjectName("dstPortLineEdit")
        self.horizontalLayout_15.addWidget(self.dstPortLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_15, 1, 0, 1, 2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ackLabel = QtWidgets.QLabel(self.groupBox_3)
        self.ackLabel.setObjectName("ackLabel")
        self.horizontalLayout_16.addWidget(self.ackLabel)
        self.ackLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.ackLineEdit.setObjectName("ackLineEdit")
        self.horizontalLayout_16.addWidget(self.ackLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 1, 2, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lenCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.lenCheckbox.setObjectName("lenCheckbox")
        self.horizontalLayout_18.addWidget(self.lenCheckbox)
        self.lenLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lenLineEdit.setText("")
        self.lenLineEdit.setObjectName("lenLineEdit")
        self.horizontalLayout_18.addWidget(self.lenLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.reservedLabel = QtWidgets.QLabel(self.groupBox_3)
        self.reservedLabel.setObjectName("reservedLabel")
        self.horizontalLayout_23.addWidget(self.reservedLabel)
        self.reservedLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.reservedLineEdit.setObjectName("reservedLineEdit")
        self.horizontalLayout_23.addWidget(self.reservedLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_23, 2, 1, 2, 3)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.checksumHeaderCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checksumHeaderCheckbox.setObjectName("checksumHeaderCheckbox")
        self.horizontalLayout_19.addWidget(self.checksumHeaderCheckbox)
        self.checksumLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.checksumLineEdit.setText("")
        self.checksumLineEdit.setObjectName("checksumLineEdit")
        self.horizontalLayout_19.addWidget(self.checksumLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_19, 3, 0, 2, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.optionsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.optionsLabel.setObjectName("optionsLabel")
        self.horizontalLayout_22.addWidget(self.optionsLabel)
        self.optionsLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.optionsLineEdit.setText("")
        self.optionsLineEdit.setObjectName("optionsLineEdit")
        self.horizontalLayout_22.addWidget(self.optionsLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_22, 4, 1, 2, 3)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.windowCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.windowCheckbox.setObjectName("windowCheckbox")
        self.horizontalLayout_20.addWidget(self.windowCheckbox)
        self.windowLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.windowLineEdit.setObjectName("windowLineEdit")
        self.horizontalLayout_20.addWidget(self.windowLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_20, 5, 0, 2, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.urgCheckbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.urgCheckbox.setObjectName("urgCheckbox")
        self.horizontalLayout_21.addWidget(self.urgCheckbox)
        self.urgPtrLabel = QtWidgets.QLabel(self.groupBox_3)
        self.urgPtrLabel.setEnabled(False)
        self.urgPtrLabel.setObjectName("urgPtrLabel")
        self.horizontalLayout_21.addWidget(self.urgPtrLabel)
        self.urgPtrLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.urgPtrLineEdit.setEnabled(False)
        self.urgPtrLineEdit.setText("")
        self.urgPtrLineEdit.setObjectName("urgPtrLineEdit")
        self.horizontalLayout_21.addWidget(self.urgPtrLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_21, 6, 1, 1, 3)
        self.addToListPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.addToListPushButton.setObjectName("addToListPushButton")
        self.gridLayout_4.addWidget(self.addToListPushButton, 7, 3, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 5, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dataLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataLabel.sizePolicy().hasHeightForWidth())
        self.dataLabel.setSizePolicy(sizePolicy)
        self.dataLabel.setMinimumSize(QtCore.QSize(967, 18))
        self.dataLabel.setMaximumSize(QtCore.QSize(967, 18))
        self.dataLabel.setObjectName("dataLabel")
        self.verticalLayout_3.addWidget(self.dataLabel)
        self.dataTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.dataTextEdit.setObjectName("dataTextEdit")
        self.verticalLayout_3.addWidget(self.dataTextEdit)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 6, 0, 1, 2)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Packet Generator by Tsvetkov"))
        self.packetLabel.setText(_translate("mainWindow", "Packet List:"))
        self.addListPushButton.setText(_translate("mainWindow", "Add to queue"))
        self.removeListPushButton.setText(_translate("mainWindow", "Remove"))
        self.packetTypeBox.setItemText(0, _translate("mainWindow", "TCP"))
        self.packetTypeBox.setItemText(1, _translate("mainWindow", "UDP"))
        self.packetTypeBox.setItemText(2, _translate("mainWindow", "ICMP - echo request"))
        self.packetTypeBox.setItemText(3, _translate("mainWindow", "ICMP - echo reply"))
        self.adaptersBox.setItemText(0, _translate("mainWindow", "Choose network interface"))
        self.packetNameLabel.setText(_translate("mainWindow", "Packet Name:"))
        self.groupBox.setTitle(_translate("mainWindow", "Data link layer - Ethernet"))
        self.srcCheckbox.setText(_translate("mainWindow", "SRC:"))
        self.dstCheckbox.setText(_translate("mainWindow", "DST:"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Network layer - IPv4"))
        self.lenIpCheckbox.setText(_translate("mainWindow", "LEN:"))
        self.lenIpLineEdit.setText(_translate("mainWindow", "0"))
        self.offsetLabel.setText(_translate("mainWindow", "OFFSET:"))
        self.offsetLineEdit.setText(_translate("mainWindow", "0"))
        self.flag0Checkbox.setText(_translate("mainWindow", "0"))
        self.flagDfCheckbox.setText(_translate("mainWindow", "DF"))
        self.flagMfCheckbox.setText(_translate("mainWindow", "MF"))
        self.checksumCheckbox.setText(_translate("mainWindow", "CHECKSUM:"))
        self.optionsIpLabel.setText(_translate("mainWindow", "OPTIONS:"))
        self.idLabel.setText(_translate("mainWindow", "ID:"))
        self.idLineEdit.setText(_translate("mainWindow", "0"))
        self.srcIpCheckbox.setText(_translate("mainWindow", "SRC IP:"))
        self.dstIpLabel.setText(_translate("mainWindow", "DST IP:"))
        self.dscpLabel.setText(_translate("mainWindow", "DSCP (Priority):"))
        self.dscpIpLineEdit.setText(_translate("mainWindow", "0"))
        self.srcVerCheckbox.setText(_translate("mainWindow", "VER:"))
        self.verLineEdit.setText(_translate("mainWindow", "4"))
        self.ttlLabel.setText(_translate("mainWindow", "TTL:"))
        self.ttlLineEdit.setText(_translate("mainWindow", "64"))
        self.queueLabel.setText(_translate("mainWindow", "Packet Sending Queue:"))
        self.sendQueuePushButton.setText(_translate("mainWindow", "Send"))
        self.removeQueuePushButton.setText(_translate("mainWindow", "Remove"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Transport level"))
        self.srcPortLabel.setText(_translate("mainWindow", "SRC PORT:"))
        self.snLabel.setText(_translate("mainWindow", "SN:"))
        self.snLineEdit.setText(_translate("mainWindow", "0"))
        self.synCheckbox.setText(_translate("mainWindow", "SYN"))
        self.pshCheckbox.setText(_translate("mainWindow", "PSH"))
        self.ackCheckbox.setText(_translate("mainWindow", "ACK"))
        self.rstCheckbox.setText(_translate("mainWindow", "RST"))
        self.finCheckbox.setText(_translate("mainWindow", "FIN"))
        self.dstPortLabel.setText(_translate("mainWindow", "DST PORT:"))
        self.ackLabel.setText(_translate("mainWindow", "ACK SN:"))
        self.ackLineEdit.setText(_translate("mainWindow", "0"))
        self.lenCheckbox.setText(_translate("mainWindow", "LEN:"))
        self.reservedLabel.setText(_translate("mainWindow", "RESERVED:"))
        self.reservedLineEdit.setText(_translate("mainWindow", "0"))
        self.checksumHeaderCheckbox.setText(_translate("mainWindow", "CHECKSUM:"))
        self.optionsLabel.setText(_translate("mainWindow", "OPTIONS:"))
        self.windowCheckbox.setText(_translate("mainWindow", "WINDOW:"))
        self.windowLineEdit.setText(_translate("mainWindow", "0"))
        self.urgCheckbox.setText(_translate("mainWindow", "URG"))
        self.urgPtrLabel.setText(_translate("mainWindow", "URG PTR:"))
        self.addToListPushButton.setText(_translate("mainWindow", "Add to list"))
        self.dataLabel.setText(_translate("mainWindow", "Data:"))
